export enum QueueName {
    TICKET_CREATE = "TICKET_CREATE",
    TICKET_UPDATE = 'TICKET_UPDATE',
    ORDER_CREATE = "ORDER_CREATE",
    ORDER_DELETE = "ORDER_DELETE",
    ORDER_EXPIRATION = "ORDER_EXPIRATION",
    EXPIRATION_COMPLETE = "EXPIRATION_COMPLETE"
}