export enum QueueName {
    TICKET_CREATE = "TICKET_CREATE",
    TICKET_UPDATE = 'TICKET_UPDATE',
    ORDER_CREATE = "ORDER_CREATE",
    PAYMENT_CREATE = "PAYMENT_CREATE",
    ORDER_CANCEL = "ORDER_CANCEL"
}