apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: serkansoy/auth
          env:
            - name: JWT_KEY
              value: "mysecretkey"
            - name: MONGO_URI
              value: "mongodb+srv://doadmin:63f8c2s9Ud4GbO51@db-mongodb-fra1-47888-2248d03c.mongo.ondigitalocean.com/auth?replicaSet=db-mongodb-fra1-47888&ssl=true&authSource=admin"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
