apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: serkansoy/payments
          env:
            - name: JWT_KEY
              value: "mysecretkey"
            - name: MONGO_URI
              value: "mongodb+srv://doadmin:63f8c2s9Ud4GbO51@db-mongodb-fra1-47888-2248d03c.mongo.ondigitalocean.com/payments?replicaSet=db-mongodb-fra1-47888&ssl=true&authSource=admin"
            - name: RabbitMQ_URI
              value: "amqps://orbnjqbv:EFzRd6FnyEiF5eJ3-tkew2lyIa99zsFT@roedeer.rmq.cloudamqp.com/orbnjqbv"
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
